# Generated by Django 3.1.3 on 2020-11-19 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary_name', models.CharField(max_length=255, verbose_name='Название словаря')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец словаря')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словари',
                'ordering': ('dictionary_name',),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_meaning', models.CharField(max_length=255, verbose_name='Значение на родном языке')),
                ('foreign_meaning', models.CharField(max_length=255, verbose_name='Значение на иностранном языке')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionary', verbose_name='Словарь')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ('dictionary',),
            },
        ),
    ]
